const fs = require('fs');
const path = require('path');

// Load .env file
const envPath = path.resolve(__dirname, '..', '.env');
const envVars = {};

if (fs.existsSync(envPath)) {
  const lines = fs.readFileSync(envPath, 'utf-8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const [key, ...rest] = trimmed.split('=');
    envVars[key.trim()] = rest.join('=').trim();
  }
}

// Override with actual environment variables (for Docker/CI)
const SUPABASE_URL = process.env.SUPABASE_URL || envVars.SUPABASE_URL || 'SUPABASE_URL_PLACEHOLDER';
const SUPABASE_KEY = process.env.SUPABASE_KEY || envVars.SUPABASE_KEY || 'SUPABASE_KEY_PLACEHOLDER';
const BINANCE_WS_URL = process.env.BINANCE_WS_URL || envVars.BINANCE_WS_URL || 'wss://stream.binance.com:9443/stream';

const targetPath = path.resolve(__dirname, '..', 'src', 'environments', 'environment.ts');

const content = `// AUTO-GENERATED by scripts/set-env.js — DO NOT EDIT
export const environment = {
  supabaseUrl: '${SUPABASE_URL}',
  supabaseKey: '${SUPABASE_KEY}',
  binanceWsUrl: '${BINANCE_WS_URL}',
};
`;

fs.writeFileSync(targetPath, content);
console.log('✔ Environment file generated at', targetPath);
